# Site settings
title: Raffi Hovhannesian
title2: My Personal Playground
header-img: img/home-bg.jpg
email: hovhannesian@gmail.com
description: "Blogging about web development technologies plus some tips and tricks."
baseurl: ""
url: "http://hovhannesian.com"
twitter_username: raffi_001
github_username:  Raffi-001
facebook_username:  hovhannesian

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
